// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransformersBattleSimulator;

#nullable disable

namespace TransformersBattleSimulator.Migrations
{
    [DbContext(typeof(BattleSimulatorDbContext))]
    partial class BattleSimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TransformersBattleSimulator.SimpleBattleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Winner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BattleResults");
                });

            modelBuilder.Entity("TransformersBattleSimulator.TransformerBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfDraws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransformerType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transformers");

                    b.HasDiscriminator<string>("TransformerType").HasValue("TransformerBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TransformersBattleSimulator.AutoBotTransformer", b =>
                {
                    b.HasBaseType("TransformersBattleSimulator.TransformerBase");

                    b.HasDiscriminator().HasValue("AutoBotTransformer");
                });

            modelBuilder.Entity("TransformersBattleSimulator.DecepticonTransformer", b =>
                {
                    b.HasBaseType("TransformersBattleSimulator.TransformerBase");

                    b.HasDiscriminator().HasValue("DecepticonTransformer");
                });
#pragma warning restore 612, 618
        }
    }
}
